POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfQURNSU5dIiwibmJmIjoxNzIwMzAwNTYxLCJleHAiOjE3MjAzMDQxNjEsImlhdCI6MTcyMDMwMDU2MSwidXNlcm5hbWUiOiJlYS5wcm9qZWN0LmFzc2lzdGFudEBnbWFpbC5jb20ifQ.7LcNPyAnYlmEbSW_Yc38rltD0bfUASvZrJv3pTU467I
Content-Type: application/json

{
    "name": "Dolci"
}

###

POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfQURNSU5dIiwibmJmIjoxNzIwMzAwNTYxLCJleHAiOjE3MjAzMDQxNjEsImlhdCI6MTcyMDMwMDU2MSwidXNlcm5hbWUiOiJlYS5wcm9qZWN0LmFzc2lzdGFudEBnbWFpbC5jb20ifQ.7LcNPyAnYlmEbSW_Yc38rltD0bfUASvZrJv3pTU467I
Content-Type: application/json

{
    "name": "Salumi"
}

###

POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfQURNSU5dIiwibmJmIjoxNzIwMzAwNTYxLCJleHAiOjE3MjAzMDQxNjEsImlhdCI6MTcyMDMwMDU2MSwidXNlcm5hbWUiOiJlYS5wcm9qZWN0LmFzc2lzdGFudEBnbWFpbC5jb20ifQ.7LcNPyAnYlmEbSW_Yc38rltD0bfUASvZrJv3pTU467I
Content-Type: application/json

{
    "name": "Verdure"
}

###

POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfQURNSU5dIiwibmJmIjoxNzIwMzAwNTYxLCJleHAiOjE3MjAzMDQxNjEsImlhdCI6MTcyMDMwMDU2MSwidXNlcm5hbWUiOiJlYS5wcm9qZWN0LmFzc2lzdGFudEBnbWFpbC5jb20ifQ.7LcNPyAnYlmEbSW_Yc38rltD0bfUASvZrJv3pTU467I
Content-Type: application/json

{
    "name": "Formaggi"
}

###

POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfQURNSU5dIiwibmJmIjoxNzIwMzAwNTYxLCJleHAiOjE3MjAzMDQxNjEsImlhdCI6MTcyMDMwMDU2MSwidXNlcm5hbWUiOiJlYS5wcm9qZWN0LmFzc2lzdGFudEBnbWFpbC5jb20ifQ.7LcNPyAnYlmEbSW_Yc38rltD0bfUASvZrJv3pTU467I
Content-Type: application/json

{
    "name": "Liquori"
}

###

POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfQURNSU5dIiwibmJmIjoxNzIwMzAwNTYxLCJleHAiOjE3MjAzMDQxNjEsImlhdCI6MTcyMDMwMDU2MSwidXNlcm5hbWUiOiJlYS5wcm9qZWN0LmFzc2lzdGFudEBnbWFpbC5jb20ifQ.7LcNPyAnYlmEbSW_Yc38rltD0bfUASvZrJv3pTU467I
Content-Type: application/json

{
    "name": "Frutta secca"
}

###

POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfQURNSU5dIiwibmJmIjoxNzIwMzAwNTYxLCJleHAiOjE3MjAzMDQxNjEsImlhdCI6MTcyMDMwMDU2MSwidXNlcm5hbWUiOiJlYS5wcm9qZWN0LmFzc2lzdGFudEBnbWFpbC5jb20ifQ.7LcNPyAnYlmEbSW_Yc38rltD0bfUASvZrJv3pTU467I
Content-Type: application/json

{
    "name": "Conserve"
}

###

POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfQURNSU5dIiwibmJmIjoxNzIwMzAwNTYxLCJleHAiOjE3MjAzMDQxNjEsImlhdCI6MTcyMDMwMDU2MSwidXNlcm5hbWUiOiJlYS5wcm9qZWN0LmFzc2lzdGFudEBnbWFpbC5jb20ifQ.7LcNPyAnYlmEbSW_Yc38rltD0bfUASvZrJv3pTU467I
Content-Type: application/json

{
    "name": "Vini"
}

###

POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfQURNSU5dIiwibmJmIjoxNzIwMzAwNTYxLCJleHAiOjE3MjAzMDQxNjEsImlhdCI6MTcyMDMwMDU2MSwidXNlcm5hbWUiOiJlYS5wcm9qZWN0LmFzc2lzdGFudEBnbWFpbC5jb20ifQ.7LcNPyAnYlmEbSW_Yc38rltD0bfUASvZrJv3pTU467I
Content-Type: application/json

{
    "name": "Miele"
}

###

POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfQURNSU5dIiwibmJmIjoxNzIwMzAwNTYxLCJleHAiOjE3MjAzMDQxNjEsImlhdCI6MTcyMDMwMDU2MSwidXNlcm5hbWUiOiJlYS5wcm9qZWN0LmFzc2lzdGFudEBnbWFpbC5jb20ifQ.7LcNPyAnYlmEbSW_Yc38rltD0bfUASvZrJv3pTU467I
Content-Type: application/json

{
    "name": "Specialit\u00e0"
}

###

POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfQURNSU5dIiwibmJmIjoxNzIwMzAwNTYxLCJleHAiOjE3MjAzMDQxNjEsImlhdCI6MTcyMDMwMDU2MSwidXNlcm5hbWUiOiJlYS5wcm9qZWN0LmFzc2lzdGFudEBnbWFpbC5jb20ifQ.7LcNPyAnYlmEbSW_Yc38rltD0bfUASvZrJv3pTU467I
Content-Type: application/json

{
    "name": "Pane"
}

###

POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfQURNSU5dIiwibmJmIjoxNzIwMzAwNTYxLCJleHAiOjE3MjAzMDQxNjEsImlhdCI6MTcyMDMwMDU2MSwidXNlcm5hbWUiOiJlYS5wcm9qZWN0LmFzc2lzdGFudEBnbWFpbC5jb20ifQ.7LcNPyAnYlmEbSW_Yc38rltD0bfUASvZrJv3pTU467I
Content-Type: application/json

{
    "name": "Gelati"
}

###

POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfQURNSU5dIiwibmJmIjoxNzIwMzAwNTYxLCJleHAiOjE3MjAzMDQxNjEsImlhdCI6MTcyMDMwMDU2MSwidXNlcm5hbWUiOiJlYS5wcm9qZWN0LmFzc2lzdGFudEBnbWFpbC5jb20ifQ.7LcNPyAnYlmEbSW_Yc38rltD0bfUASvZrJv3pTU467I
Content-Type: application/json

{
    "name": "Creme"
}

###

