
POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfVVNFUl0iLCJuYmYiOjE3MjAyNTEzMDcsImV4cCI6MTcyMDI1NDkwNywiaWF0IjoxNzIwMjUxMzA3LCJ1c2VybmFtZSI6ImZyYW5jZXNjb3ZlY2NoaW8wMUBnbWFpbC5jb20ifQ.TVXMVzisMvs0dlvKosPbw2KxTLjr6-V9bYZw7RF3kDs
Content-Type: application/json

{
  "name": "Dolci"
}

###
POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfVVNFUl0iLCJuYmYiOjE3MjAyNTEzMDcsImV4cCI6MTcyMDI1NDkwNywiaWF0IjoxNzIwMjUxMzA3LCJ1c2VybmFtZSI6ImZyYW5jZXNjb3ZlY2NoaW8wMUBnbWFpbC5jb20ifQ.TVXMVzisMvs0dlvKosPbw2KxTLjr6-V9bYZw7RF3kDs
Content-Type: application/json

{
  "name": "Salumi"
}

###
POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfVVNFUl0iLCJuYmYiOjE3MjAyNTEzMDcsImV4cCI6MTcyMDI1NDkwNywiaWF0IjoxNzIwMjUxMzA3LCJ1c2VybmFtZSI6ImZyYW5jZXNjb3ZlY2NoaW8wMUBnbWFpbC5jb20ifQ.TVXMVzisMvs0dlvKosPbw2KxTLjr6-V9bYZw7RF3kDs
Content-Type: application/json

{
  "name": "Verdure"
}

###
POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfVVNFUl0iLCJuYmYiOjE3MjAyNTEzMDcsImV4cCI6MTcyMDI1NDkwNywiaWF0IjoxNzIwMjUxMzA3LCJ1c2VybmFtZSI6ImZyYW5jZXNjb3ZlY2NoaW8wMUBnbWFpbC5jb20ifQ.TVXMVzisMvs0dlvKosPbw2KxTLjr6-V9bYZw7RF3kDs
Content-Type: application/json

{
  "name": "Formaggi"
}

###
POST http://localhost:8080/api/v1/category/addCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiW1JPTEVfVVNFUl0iLCJuYmYiOjE3MjAyNTEzMDcsImV4cCI6MTcyMDI1NDkwNywiaWF0IjoxNzIwMjUxMzA3LCJ1c2VybmFtZSI6ImZyYW5jZXNjb3ZlY2NoaW8wMUBnbWFpbC5jb20ifQ.TVXMVzisMvs0dlvKosPbw2KxTLjr6-V9bYZw7RF3kDs
Content-Type: application/json

{
  "name": "Liquori"
}
